auto_deploy: true

environment_templates:
  - name: ephemeral

resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1

infrastructure:
  - name: lambda
    type: terraform
    directory: "./terraform"
    values: ".release/values.tfvar"

workflows:
  - name: setup
    order_from:
      - infrastructure.lambda
  - name: patch
    order_from:
      - infrastructure.lambda
  - name: teardown
    order_from:
      - release.remove_environment