app: terraform-runner-example
auto_deploy: true
context: hubofhubs-release-us-west-2
domain: release.hubofhubs.com
repo_name: releasehub-samples/terraform-runner-example

environment_templates:
  - name: ephemeral

resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1

infrastructure:
  - name: terraform-demo
    type: terraform
    directory: "./terraform"
    values: "./terraform/variables.tfvar"

workflows:
  - name: setup
    order_from:
      - infrastructure.terraform-demo
  - name: patch
    order_from:
      - infrastructure.terraform-demo
  - name: teardown
    order_from:
      - release.remove_environment